### PR TITLE
Update /usr/libexec/cockpit-session owner

### PR DESCRIPTION
**Pull request by martinpitt**
The ownership changed in Cockpit 207 [1] four years ago.

[1] https://github.com/cockpit-project/cockpit/commit/6b7da2f0169fc1

---

This should fix the [rpminspect failures](https://artifacts.dev.testing-farm.io/0b4f0f1e-e234-4cf3-8dbd-25f29ba1d36b/) of cockpit.

### CODE REVIEW

**Comment by martinpitt** [comment]
@dcantrell can you please have a look? thanks!

**Comment by martinpitt** [comment]
Gentle ping?

**Comment by dcantrell** [comment]
I was on PTO from 23-Aug to 25-Aug and am back in the office now.  This data package is probably better to have in a group maintenance place, similar to rpminspect-data-centos.  I am open to suggestions.

**Comment by martinpitt** [comment]
Thanks @dcantrell ! I hope you had some more holidays than just two days :grin:

**Pull request merged**
